/**
 * The registry, derived from the directories rather than typed out.
 *
 * `candidates/registry.ts` used to be `candidates/index.ts`'s array, and every
 * lane that opened a slot added one import and one line to it. That is fine
 * while one lane is open and a rebase conflict every time once several are —
 * and the queue this was written for holds a dozen lanes that each open a slot.
 * The conflict is the worst kind, too: two sessions colliding in a file neither
 * of them is really changing, in the middle of landing work that is finished.
 *
 * So the array is generated from what is on disk. `bun run versus index`
 * rewrites it, a conflict in it is resolved by running that command rather
 * than by reading either side, and `test/registry.test.ts` fails when the file
 * and the directories disagree. `candidates/index.ts` keeps the prose and
 * re-exports, because the argument for how this is arranged is worth reading
 * at the place it is used and is not worth regenerating.
 *
 * The order is the directory order, which groups a slot's answers together
 * because a slot's directory name is their shared prefix. The array used to be
 * in the order candidates were registered, which was the order somebody typed
 * them in.
 */

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { dirsIn } from "./slots.js";
import { quoted } from "./text.js";

/** One candidate directory, and the symbol its `index.ts` exports. */
export interface Registered {
  /** `creature-meteor/forge`, as the import specifier spells it. */
  readonly path: string;
  /** `METEOR_FORGE`. */
  readonly symbol: string;
  /** Repo-relative, the way `Variant.dir` spells it. */
  readonly dir: string;
}

const HEAD = `// Generated by \`bun run versus index\` — do not edit.
//
// Every candidate directory under \`candidates/\`, in directory order. Add one by
// making the directory and running the command; a conflict here is resolved the
// same way. \`test/registry.test.ts\` fails when this and the tree disagree, and
// \`index.ts\` next door says why it is generated at all.
`;

/**
 * Every candidate on disk. A directory is a candidate when it is two levels
 * down from `candidates/` and holds an `index.ts` exporting a `Variant`; a
 * directory that holds only a `paint.ts` is half a candidate and is reported as
 * one that could not be read, rather than skipped silently — and `unreadable`
 * below says which half is missing.
 */
export function discover(candidatesDir: string): Registered[] {
  const found: Registered[] = [];
  for (const slot of dirsIn(candidatesDir)) {
    for (const name of dirsIn(join(candidatesDir, slot))) {
      const file = join(candidatesDir, slot, name, "index.ts");
      const symbol = exportedVariant(readOr(file));
      if (!symbol) throw new Error(unreadable(candidatesDir, slot, name));
      found.push({
        path: `${slot}/${name}`,
        symbol,
        dir: `tools/versus/candidates/${slot}/${name}`,
      });
    }
  }
  return found.sort((a, b) => (a.path < b.path ? -1 : 1));
}

function readOr(file: string): string {
  try {
    return readFileSync(file, "utf8");
  } catch {
    return "";
  }
}

/** `export const METEOR_FORGE: Variant = {` — the one line that names a candidate. */
function exportedVariant(src: string): string | undefined {
  return /export\s+const\s+([A-Z][A-Z0-9_]*)\s*:\s*Variant\b/.exec(src)?.[1];
}

/** The files directly in a directory, dotfiles aside. */
function filesIn(path: string): string[] {
  return readdirSync(path, { withFileTypes: true })
    .filter((e) => e.isFile() && !e.name.startsWith("."))
    .map((e) => e.name)
    .sort();
}

/**
 * Why a directory under `candidates/` is not a candidate, in the words the
 * lane standing over it needs.
 *
 * The three cases have three different things to do about them, and for a
 * while they had one sentence between them. A slot wants two answers, so a
 * lane opening one writes the first candidate's files and the second's a few
 * minutes later; in between there is a directory with nothing in it, and every
 * `bun run versus index` and every `bun test` until the files landed failed
 * with `lost-screen/pool/index.ts exports no const … : Variant` — true, and
 * about a file nobody had written (21 September 2026, the `lost:screen`
 * answers). An empty directory is a lane mid-sentence and is filled or
 * removed; a directory with paint in it and no `index.ts` is an answer whose
 * registration was never written; a file with no export is a typo inside one.
 *
 * Each says the repo-relative path in full, because whoever reads this is as
 * often a `git status` away from the tree as standing in it.
 */
function unreadable(candidatesDir: string, slot: string, name: string): string {
  const dir = `tools/versus/candidates/${slot}/${name}`;
  const held = filesIn(join(candidatesDir, slot, name));
  if (held.length === 0) {
    return `${dir}/ is empty — write its \`index.ts\`, or remove the directory`;
  }
  if (!held.includes("index.ts")) {
    return (
      `${dir}/ holds ${quoted(held)} and no \`index.ts\` — a candidate is the ` +
      "`index.ts` that exports its `Variant`, and the paint beside it"
    );
  }
  return `${dir}/index.ts exports no \`const … : Variant\``;
}

/** Biome's `lineWidth`, from `biome.json`. The one number this file shares
 * with the formatter it has to agree with. */
const LINE_WIDTH = 100;

/** The whole of `candidates/registry.ts`, as it should read right now. */
export function registryText(found: readonly Registered[]): string {
  const imports = found.map((f) => `import { ${f.symbol} } from "./${f.path}/index.js";`);
  const entries = found.map((f) => `  ${f.symbol},`);
  // **Printed the way Biome would print it, because this file is linted.** An
  // array that fits on one line is collapsed onto one line by the formatter,
  // so a generator that always spread it made `bun run lint` red on a
  // generated file every time a slot came down to a single answer — which is
  // how the empty case came to be special-cased here on 12 September 2026 and
  // how the one-entry case was found red on 17 September. The rule is the
  // formatter's own and covers every count, the empty list included.
  const one = `export const VARIANTS: Variant[] = [${found.map((f) => f.symbol).join(", ")}];`;
  const list =
    one.length <= LINE_WIDTH ? [one] : [`export const VARIANTS: Variant[] = [`, ...entries, `];`];
  return [HEAD, `import type { Variant } from "../variant.js";`, ...imports, "", ...list, ""].join(
    "\n",
  );
}

/** Rewrite the file, and say whether it had anything to change. */
export function writeRegistry(candidatesDir: string): { changed: boolean; count: number } {
  const found = discover(candidatesDir);
  const file = join(candidatesDir, "registry.ts");
  const next = registryText(found);
  const changed = readOr(file) !== next;
  if (changed) writeFileSync(file, next);
  return { changed, count: found.length };
}
