/**
 * The registry, derived from the directories rather than typed out.
 *
 * `candidates/registry.ts` used to be `candidates/index.ts`'s array, and every
 * lane that opened a slot added one import and one line to it. That is fine
 * while one lane is open and a rebase conflict every time once several are —
 * and the queue this was written for holds a dozen lanes that each open a slot.
 * The conflict is the worst kind, too: two sessions colliding in a file neither
 * of them is really changing, in the middle of landing work that is finished.
 *
 * So the array is generated from what is on disk. `bun run versus index`
 * rewrites it, a conflict in it is resolved by running that command rather
 * than by reading either side, and `test/registry.test.ts` fails when the file
 * and the directories disagree. `candidates/index.ts` keeps the prose and
 * re-exports, because the argument for how this is arranged is worth reading
 * at the place it is used and is not worth regenerating.
 *
 * The order is the directory order, which groups a slot's answers together
 * because a slot's directory name is their shared prefix. The array used to be
 * in the order candidates were registered, which was the order somebody typed
 * them in.
 */

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

/** One candidate directory, and the symbol its `index.ts` exports. */
export interface Registered {
  /** `creature-meteor/forge`, as the import specifier spells it. */
  readonly path: string;
  /** `METEOR_FORGE`. */
  readonly symbol: string;
  /** Repo-relative, the way `Variant.dir` spells it. */
  readonly dir: string;
}

const HEAD = `// Generated by \`bun run versus index\` — do not edit.
//
// Every candidate directory under \`candidates/\`, in directory order. Add one by
// making the directory and running the command; a conflict here is resolved the
// same way. \`test/registry.test.ts\` fails when this and the tree disagree, and
// \`index.ts\` next door says why it is generated at all.
`;

/**
 * Every candidate on disk. A directory is a candidate when it is two levels
 * down from `candidates/` and holds an `index.ts` exporting a `Variant`; a
 * directory that holds only a `paint.ts` is half a candidate and is reported as
 * one that could not be read, rather than skipped silently.
 */
export function discover(candidatesDir: string): Registered[] {
  const found: Registered[] = [];
  for (const slot of dirsIn(candidatesDir)) {
    for (const name of dirsIn(join(candidatesDir, slot))) {
      const file = join(candidatesDir, slot, name, "index.ts");
      const symbol = exportedVariant(readOr(file));
      if (!symbol) throw new Error(`${slot}/${name}/index.ts exports no \`const … : Variant\``);
      found.push({
        path: `${slot}/${name}`,
        symbol,
        dir: `tools/versus/candidates/${slot}/${name}`,
      });
    }
  }
  return found.sort((a, b) => (a.path < b.path ? -1 : 1));
}

/**
 * A dot-directory is never a candidate, and `.claude` in particular holds a
 * lane's own checkout of the whole repository — a walk that descended into one
 * would find every candidate twice. `tools/test/tree-walk.test.ts` holds every
 * walk in the repository to skipping it, and it is right to be blunt about it:
 * the scope this one is called with makes the case impossible today, and the
 * next caller is what the rule is for.
 */
const SKIP = new Set([".claude", "node_modules", "dist"]);

function dirsIn(path: string): string[] {
  return readdirSync(path, { withFileTypes: true })
    .filter((e) => e.isDirectory() && !SKIP.has(e.name) && !e.name.startsWith("."))
    .map((e) => e.name)
    .sort();
}

function readOr(file: string): string {
  try {
    return readFileSync(file, "utf8");
  } catch {
    return "";
  }
}

/** `export const METEOR_FORGE: Variant = {` — the one line that names a candidate. */
function exportedVariant(src: string): string | undefined {
  return /export\s+const\s+([A-Z][A-Z0-9_]*)\s*:\s*Variant\b/.exec(src)?.[1];
}

/** Biome's `lineWidth`, from `biome.json`. The one number this file shares
 * with the formatter it has to agree with. */
const LINE_WIDTH = 100;

/** The whole of `candidates/registry.ts`, as it should read right now. */
export function registryText(found: readonly Registered[]): string {
  const imports = found.map((f) => `import { ${f.symbol} } from "./${f.path}/index.js";`);
  const entries = found.map((f) => `  ${f.symbol},`);
  // **Printed the way Biome would print it, because this file is linted.** An
  // array that fits on one line is collapsed onto one line by the formatter,
  // so a generator that always spread it made `bun run lint` red on a
  // generated file every time a slot came down to a single answer — which is
  // how the empty case came to be special-cased here on 12 September 2026 and
  // how the one-entry case was found red on 17 September. The rule is the
  // formatter's own and covers every count, the empty list included.
  const one = `export const VARIANTS: Variant[] = [${found.map((f) => f.symbol).join(", ")}];`;
  const list =
    one.length <= LINE_WIDTH ? [one] : [`export const VARIANTS: Variant[] = [`, ...entries, `];`];
  return [HEAD, `import type { Variant } from "../variant.js";`, ...imports, "", ...list, ""].join(
    "\n",
  );
}

/** Rewrite the file, and say whether it had anything to change. */
export function writeRegistry(candidatesDir: string): { changed: boolean; count: number } {
  const found = discover(candidatesDir);
  const file = join(candidatesDir, "registry.ts");
  const next = registryText(found);
  const changed = readOr(file) !== next;
  if (changed) writeFileSync(file, next);
  return { changed, count: found.length };
}

/** `creature:torch` -> `creature-torch`, the directory a slot's answers share. */
export function slotDir(slot: string): string {
  return slot.replace(":", "-");
}

/**
 * `creature-torch` -> `creature:torch`, the way back. A slot name carries one
 * colon and its directory carries a dash in that one place, so the *first* dash
 * is the one that was a colon and the rest belong to the name:
 * `panel-ship-join` is `panel:ship-join`.
 */
export function slotOfDir(dir: string): string {
  return dir.replace("-", ":");
}

/** One candidate, as its directory names it — all a slot being closed needs. */
export interface OnDisk {
  /** This answer, one word, which is its directory's name. */
  readonly name: string;
  /** Repo-relative, the way `Variant.dir` spells it. */
  readonly dir: string;
}

/**
 * One slot's candidates, read off the directory names and nothing else.
 *
 * `discover` opens every `index.ts`, because a registry has to name the symbol
 * inside it. This opens nothing, and that is the whole of its job. `drop`
 * closes a slot after the by-hand sequence `adopt` prints when it refuses a
 * function — move the paint into the package, rewrite the record, delete what
 * nothing reads — and that sequence leaves the slot's modules unimportable:
 * the moved file is gone from the candidate that had it, and the shipped
 * module it came from has lost exports the *other* candidates were composing.
 * A `drop` that had to import them could not run at the one moment it is
 * prescribed for (`lost:screen` / `shut`, 17 September 2026).
 *
 * A slot with no directory and a directory with nothing in it are the same
 * answer — no candidates — and the caller says so in its own words.
 */
export function candidatesIn(candidatesDir: string, slot: string): OnDisk[] {
  const dir = slotDir(slot);
  let names: string[];
  try {
    names = dirsIn(join(candidatesDir, dir));
  } catch {
    return [];
  }
  return names.map((name) => ({ name, dir: `tools/versus/candidates/${dir}/${name}` }));
}

/** Every slot with a directory under `candidates/`, named the way it is asked for. */
export function slotsOnDisk(candidatesDir: string): string[] {
  return dirsIn(candidatesDir).map(slotOfDir);
}
