import a00 from "../../../assets/gallery/explosions/absorption/00.png";
import a01 from "../../../assets/gallery/explosions/absorption/01.png";
import a02 from "../../../assets/gallery/explosions/absorption/02.png";
import a03 from "../../../assets/gallery/explosions/absorption/03.png";
import a04 from "../../../assets/gallery/explosions/absorption/04.png";
import a05 from "../../../assets/gallery/explosions/absorption/05.png";
import a06 from "../../../assets/gallery/explosions/absorption/06.png";
import a07 from "../../../assets/gallery/explosions/absorption/07.png";
import a08 from "../../../assets/gallery/explosions/absorption/08.png";
import s00 from "../../../assets/gallery/shield/green-shield/00.webp";
import s01 from "../../../assets/gallery/shield/green-shield/01.webp";
import s02 from "../../../assets/gallery/shield/green-shield/02.webp";
import s03 from "../../../assets/gallery/shield/green-shield/03.webp";
import s04 from "../../../assets/gallery/shield/green-shield/04.webp";
import s05 from "../../../assets/gallery/shield/green-shield/05.webp";
import s06 from "../../../assets/gallery/shield/green-shield/06.webp";
import s07 from "../../../assets/gallery/shield/green-shield/07.webp";
import s08 from "../../../assets/gallery/shield/green-shield/08.webp";
import s09 from "../../../assets/gallery/shield/green-shield/09.webp";
import s10 from "../../../assets/gallery/shield/green-shield/10.webp";
import s11 from "../../../assets/gallery/shield/green-shield/11.webp";
import s12 from "../../../assets/gallery/shield/green-shield/12.webp";
import s13 from "../../../assets/gallery/shield/green-shield/13.webp";
import s14 from "../../../assets/gallery/shield/green-shield/14.webp";
import s15 from "../../../assets/gallery/shield/green-shield/15.webp";
import s16 from "../../../assets/gallery/shield/green-shield/16.webp";
import s17 from "../../../assets/gallery/shield/green-shield/17.webp";
import s18 from "../../../assets/gallery/shield/green-shield/18.webp";
import s19 from "../../../assets/gallery/shield/green-shield/19.webp";

/**
 * "COLLECTED LOOKS" on the OTHER GRAPHICS tab: hand-painted frame sequences
 * from outside this repo, not generated by anything in it — the raw
 * material CLAUDE.md's *A look with no shipped alternative* exemption is
 * about. Each entry is a still image per frame, imported the same way
 * `raster-cards.ts` imports `burst.apng` — the bundler copies the file and
 * hands back its URL, nothing is decoded here.
 *
 * Adding one is: drop the frames under `assets/gallery/<category>/<id>/`,
 * run `bun run raster:pack` over that folder, import them above, and add one
 * entry below. `gallery-page.ts` draws whatever this array holds.
 *
 * **The frames are WebP, and that is not a preference.** Hand-painted frames
 * arrive as full-resolution PNG, which is the worst possible container for a
 * soft gradient under an alpha plane: the twenty green-shield frames were
 * 2.5 MB as 512 px PNGs and are 350 KB as 256 px WebPs, with nothing an eye
 * can find on a gallery card. `raster:pack` does the conversion and writes
 * the strip the game draws from at the same time; the masters stay in git
 * history.
 */

export type GalleryCategory = "SHIELD" | "SCAN" | "EXPLOSIONS" | "BEAM";

/** Fixed display order — a category with nothing in it yet still gets a heading. */
export const GALLERY_CATEGORIES: readonly GalleryCategory[] = [
  "SHIELD",
  "SCAN",
  "EXPLOSIONS",
  "BEAM",
];

export interface GalleryClip {
  id: string;
  name: string;
  category: GalleryCategory;
  frames: readonly string[];
  frameMs: number;
}

/** Milliseconds a frame holds before advancing — the same for every clip until one asks otherwise. */
const FRAME_MS = 70;

export const GALLERY_CLIPS: readonly GalleryClip[] = [
  {
    id: "green-shield",
    name: "Green Shield",
    category: "SHIELD",
    frameMs: FRAME_MS,
    frames: [
      s00,
      s01,
      s02,
      s03,
      s04,
      s05,
      s06,
      s07,
      s08,
      s09,
      s10,
      s11,
      s12,
      s13,
      s14,
      s15,
      s16,
      s17,
      s18,
      s19,
    ],
  },
  {
    id: "absorption",
    name: "Absorption",
    category: "EXPLOSIONS",
    frameMs: FRAME_MS,
    frames: [a00, a01, a02, a03, a04, a05, a06, a07, a08],
  },
];
