import a00 from "../../../assets/gallery/explosions/absorption/00.png";
import a01 from "../../../assets/gallery/explosions/absorption/01.png";
import a02 from "../../../assets/gallery/explosions/absorption/02.png";
import a03 from "../../../assets/gallery/explosions/absorption/03.png";
import a04 from "../../../assets/gallery/explosions/absorption/04.png";
import a05 from "../../../assets/gallery/explosions/absorption/05.png";
import a06 from "../../../assets/gallery/explosions/absorption/06.png";
import a07 from "../../../assets/gallery/explosions/absorption/07.png";
import a08 from "../../../assets/gallery/explosions/absorption/08.png";
import s00 from "../../../assets/gallery/shield/green-shield/00.png";
import s01 from "../../../assets/gallery/shield/green-shield/01.png";
import s02 from "../../../assets/gallery/shield/green-shield/02.png";
import s03 from "../../../assets/gallery/shield/green-shield/03.png";
import s04 from "../../../assets/gallery/shield/green-shield/04.png";
import s05 from "../../../assets/gallery/shield/green-shield/05.png";
import s06 from "../../../assets/gallery/shield/green-shield/06.png";
import s07 from "../../../assets/gallery/shield/green-shield/07.png";
import s08 from "../../../assets/gallery/shield/green-shield/08.png";
import s09 from "../../../assets/gallery/shield/green-shield/09.png";
import s10 from "../../../assets/gallery/shield/green-shield/10.png";
import s11 from "../../../assets/gallery/shield/green-shield/11.png";
import s12 from "../../../assets/gallery/shield/green-shield/12.png";
import s13 from "../../../assets/gallery/shield/green-shield/13.png";
import s14 from "../../../assets/gallery/shield/green-shield/14.png";
import s15 from "../../../assets/gallery/shield/green-shield/15.png";
import s16 from "../../../assets/gallery/shield/green-shield/16.png";
import s17 from "../../../assets/gallery/shield/green-shield/17.png";
import s18 from "../../../assets/gallery/shield/green-shield/18.png";
import s19 from "../../../assets/gallery/shield/green-shield/19.png";

/**
 * "COLLECTED LOOKS" on the OTHER GRAPHICS tab: hand-painted frame sequences
 * from outside this repo, not generated by anything in it — the raw
 * material CLAUDE.md's *A look with no shipped alternative* exemption is
 * about. Each entry is a still image per frame, imported the same way
 * `raster-cards.ts` imports `burst.apng` — the bundler copies the file and
 * hands back its URL, nothing is decoded here.
 *
 * Adding one is: drop the frames under `assets/gallery/<category>/<id>/`,
 * import them above, and add one entry below. `gallery-page.ts` draws
 * whatever this array holds.
 */

export type GalleryCategory = "SHIELD" | "SCAN" | "EXPLOSIONS" | "BEAM";

/** Fixed display order — a category with nothing in it yet still gets a heading. */
export const GALLERY_CATEGORIES: readonly GalleryCategory[] = [
  "SHIELD",
  "SCAN",
  "EXPLOSIONS",
  "BEAM",
];

export interface GalleryClip {
  id: string;
  name: string;
  category: GalleryCategory;
  frames: readonly string[];
  frameMs: number;
}

/** Milliseconds a frame holds before advancing — the same for every clip until one asks otherwise. */
const FRAME_MS = 70;

export const GALLERY_CLIPS: readonly GalleryClip[] = [
  {
    id: "green-shield",
    name: "Green Shield",
    category: "SHIELD",
    frameMs: FRAME_MS,
    frames: [
      s00,
      s01,
      s02,
      s03,
      s04,
      s05,
      s06,
      s07,
      s08,
      s09,
      s10,
      s11,
      s12,
      s13,
      s14,
      s15,
      s16,
      s17,
      s18,
      s19,
    ],
  },
  {
    id: "absorption",
    name: "Absorption",
    category: "EXPLOSIONS",
    frameMs: FRAME_MS,
    frames: [a00, a01, a02, a03, a04, a05, a06, a07, a08],
  },
];
