/**
 * The sounds wired up with nothing to draw, the fourth page — from THE SEAM
 * on.
 *
 * Cut off `sound-link-none-c.ts` on 26 September 2026, when THE OCULUS's
 * twelve would have put that page over its 250-line limit, by the rule the
 * pages before it carry: the *last* boss on the full page goes across, and the
 * boss being worked on comes with it. `sound-link-none.ts` spreads all four
 * into `NO_SUBJECT`, so `test/sound-link.test.ts` still reads one table.
 */
export const NO_SUBJECT_D: Record<string, string> = {
  // THE SEAM's nine: a ridge over the field, the same argument.
  "boss.seamEnter": "the ridge rising over the field. A fixture, not a body on a grid.",
  "boss.seamLight": "a step lighting on the crack. Same argument.",
  "boss.seamDim": "a point shot dark without closing. Same argument.",
  "boss.seamSeal": "a point shot shut. Same argument.",
  "boss.seamRockOut": "a rock from the crack shot out. A rock here is a target. Same argument.",
  "boss.seamBlock": "grit on the shield, which is no creature. Same argument.",
  "boss.seamMiss": "a step unanswered, on the hull, which the hull's own sounds have.",
  "boss.seamSplit": "the ridge splitting down its crack. Same argument.",
  "boss.seamOut": "the ridge gone and the wave ending. Same argument, and an absence.",
  // THE OCULUS's twelve: an eye over the field, the same argument.
  "boss.oculusEnter": "the eye rising over the field. A fixture, not a body on a grid.",
  "boss.oculusLight": "a step lighting on the eye. Same argument.",
  "boss.oculusSlip": "a thumb lifted off a leaf, which is a hold and no body. Same argument.",
  "boss.oculusShut": "two leaves shut. Same argument.",
  "boss.oculusSpring": "the leaves flying open again. Same argument.",
  "boss.oculusBreak": "the lens cracking open to its socket. Same argument.",
  "boss.oculusHit": "a shot into the socket. Same argument.",
  "boss.oculusReseal": "the socket covered over by two leaves. Same argument.",
  "boss.oculusSwallow": "the socket closing on its own. Same argument.",
  "boss.oculusMiss": "a fire step unanswered, on the hull, which the hull's own sounds have.",
  "boss.oculusShatter": "the eye bursting. Same argument.",
  "boss.oculusOut": "the eye gone and the wave ending. Same argument, and an absence.",
  // THE VISE's twelve: a case over the field, the same argument.
  "boss.viseEnter": "the case settling over the field. A fixture, not a body on a grid.",
  "boss.viseLight": "a step lighting on the case. Same argument.",
  "boss.viseSlip": "a pinch let open, which is a gesture and no body. Same argument.",
  "boss.viseCrack": "a seam cracking in a lobe. Same argument.",
  "boss.viseSpring": "a lobe springing wide again. Same argument.",
  "boss.viseBare": "both lobes split and the kernel bare. Same argument.",
  "boss.viseHit": "a shot into the kernel. Same argument.",
  "boss.viseBrace": "both lobes held off the kernel. Same argument.",
  "boss.viseCover": "the lobes closing over the kernel. Same argument.",
  "boss.viseMiss": "a fire step unanswered, on the hull, which the hull's own sounds have.",
  "boss.viseSplit": "the case splitting down its spine. Same argument.",
  "boss.viseOut": "the case gone and the wave ending. Same argument, and an absence.",
  // THE RIME's twelve: a lens over the field, the same argument.
  "boss.rimeEnter": "the lens settling over the field. A fixture, not a body on a grid.",
  "boss.rimeLight": "a step lighting on the lens. Same argument.",
  "boss.rimeShave": "frost rubbed off a half, which is a gesture and no body. Same argument.",
  "boss.rimeClear": "a half wiped clear. Same argument.",
  "boss.rimeFrost": "a half frosting over again. Same argument.",
  "boss.rimeBare": "both halves clear and the core bare. Same argument.",
  "boss.rimeHit": "a shot into the core. Same argument.",
  "boss.rimeBlock": "a surge of frost turned by the shield. Same argument.",
  "boss.rimeCloud": "the lens frosting over whole. Same argument.",
  "boss.rimeMiss": "a fire step unanswered, on the hull, which the hull's own sounds have.",
  "boss.rimeShatter": "the lens shattering. Same argument.",
  "boss.rimeOut": "the lens gone and the wave ending. Same argument, and an absence.",
  // THE TRIVET's twelve: a stand over the field, the same argument.
  "boss.trivetEnter": "the stand dropping over the field. A fixture, not a body on a grid.",
  "boss.trivetLight": "a step lighting on the stand. Same argument.",
  "boss.trivetSlip": "a pad lifted in a chord, which is a gesture and no body. Same argument.",
  "boss.trivetPlant": "a foot driven home. Same argument.",
  "boss.trivetSpring": "a foot springing back up. Same argument.",
  "boss.trivetHub": "both feet home and the hub lit. Same argument.",
  "boss.trivetHit": "a shot into the hub. Same argument.",
  "boss.trivetBrace": "both feet held under the hub. Same argument.",
  "boss.trivetRock": "the stand rocking back up, the hub dark. Same argument.",
  "boss.trivetMiss": "a fire step unanswered, on the hull, which the hull's own sounds have.",
  "boss.trivetCollapse": "the stand's three feet buckling. Same argument.",
  "boss.trivetOut": "the stand gone and the wave ending. Same argument, and an absence.",
  // THE PLUMB's twelve: a bob over the field, the same argument.
  "boss.plumbEnter": "the bob swinging in over the field. A fixture, not a body on a grid.",
  "boss.plumbLight": "a step lighting on the bob. Same argument.",
  "boss.plumbDrift": "a lean drifting off level, which is a gesture and no body. Same argument.",
  "boss.plumbSettle": "a weight settling true. Same argument.",
  "boss.plumbSwing": "a weight swinging loose. Same argument.",
  "boss.plumbCore": "both weights true and the core lit. Same argument.",
  "boss.plumbHit": "a shot into the core. Same argument.",
  "boss.plumbSteady": "both weights held true under the core. Same argument.",
  "boss.plumbDim": "the core dimming, a weight off true. Same argument.",
  "boss.plumbMiss": "a fire step unanswered, on the hull, which the hull's own sounds have.",
  "boss.plumbFree": "both weights snapping loose. Same argument.",
  "boss.plumbOut": "the bob gone and the wave ending. Same argument, and an absence.",
  // THE SLING's twelve: a fork over the field, the same argument.
  "boss.slingEnter": "the fork bolting in over the field. A fixture, not a body on a grid.",
  "boss.slingLight": "a step lighting on the fork. Same argument.",
  "boss.slingSlack": "a draw let go too soon, which is a gesture and no body. Same argument.",
  "boss.slingLoose": "a draw loosed true. Same argument.",
  "boss.slingSpring": "an arm springing back undrawn. Same argument.",
  "boss.slingYoke": "both arms drawn and the yoke lit. Same argument.",
  "boss.slingHit": "a shot into the yoke. Same argument.",
  "boss.slingSteady": "both arms redrawn under the yoke. Same argument.",
  "boss.slingDim": "the yoke springing loose. Same argument.",
  "boss.slingMiss": "a fire step unanswered, on the hull, which the hull's own sounds have.",
  "boss.slingFree": "the fork snapping forward, spent. Same argument.",
  "boss.slingOut": "the fork gone and the wave ending. Same argument, and an absence.",
  // THE GRINDSTONE's thirteen: a wheel over the field, the same argument.
  "boss.grindstoneEnter": "the wheel turning in over the field. A fixture, not a body on a grid.",
  "boss.grindstoneLight": "a step lighting on the wheel. Same argument.",
  "boss.grindstoneShave": "a flat rubbed, which is a gesture and no body. Same argument.",
  "boss.grindstoneClear": "a flat ground clean. Same argument.",
  "boss.grindstoneRegrit": "a flat gritting over again. Same argument.",
  "boss.grindstoneBite": "the caliper biting shut on the wheel. Same argument.",
  "boss.grindstoneSlip": "a pad lifting off a jaw. Same argument.",
  "boss.grindstoneClamp": "both jaws held home. Same argument.",
  "boss.grindstoneLoose": "the caliper springing loose. Same argument.",
  "boss.grindstoneHit": "a shot into the axle. Same argument.",
  "boss.grindstoneMiss": "a fire step unanswered, on the hull, which the hull's own sounds have.",
  "boss.grindstoneFree": "the wheel spinning free, spent. Same argument.",
  "boss.grindstoneOut": "the wheel gone and the wave ending. Same argument, and an absence.",
  // THE CYST's fourteen: a sac over the field, the same argument.
  "boss.cystEnter": "the sac settling in over the field. A fixture, not a body on a grid.",
  "boss.cystLight": "a step lighting on the sac. Same argument.",
  "boss.cystStill": "a flank tapped still, which is a gesture and no body. Same argument.",
  "boss.cystShudder": "a flank never stilled. Same argument.",
  "boss.cystSlip": "a pinch letting go. Same argument.",
  "boss.cystCrack": "a flank cracking. Same argument.",
  "boss.cystSpring": "a stilled flank springing wide. Same argument.",
  "boss.cystBare": "the core bared under the sac. Same argument.",
  "boss.cystHit": "a shot into the core. Same argument.",
  "boss.cystGuard": "a flank held off the core. Same argument.",
  "boss.cystSeal": "a flank closing over the core. Same argument.",
  "boss.cystMiss": "a fire step unanswered, on the hull, which the hull's own sounds have.",
  "boss.cystSplit": "the sac splitting, spent. Same argument.",
  "boss.cystOut": "the sac gone and the wave ending. Same argument, and an absence.",
};
