export {
  type ControlGroup,
  CREATURES,
  type CreatureCategory,
  type CreatureDef,
  categoryOf,
  controlsForKinds,
  kindForColor,
  POD_CATEGORY,
  type RadarOwner,
  radarOwner,
  showsRadar,
} from "./creatures.js";
export {
  type Bump,
  bumpAdd,
  bumpLift,
  hullAngleAtX,
  hullPointAtX,
  hullRadiusMul,
} from "./hull-shape.js";
export {
  AUTHORED_COL_MAX,
  AUTHORED_COLS,
  bossFromWave,
  buildBoss,
  buildPods,
  buildQueue,
  mapCol,
  podsFromWave,
  queueFromWave,
} from "./queue.js";
export {
  blobPath,
  blobRadiusMul,
  catmullRomToBezierPath,
  circleSubpath,
  crystalPath,
  crystalRadiusMul,
  openSmoothPath,
  type Point,
} from "./shapes.js";
export {
  BULB,
  CANNON_LOBE,
  type CreatureSilhouette,
  type CrystalSilhouette,
  HULL,
  HULL_GEOMETRY,
  type HullSilhouette,
  type LobeShape,
  livingSilhouette,
  MAW,
  METEOR,
  POD,
  QUEEN_SHELL,
  SHIELD_LOBE,
  SLICK,
  TORCH,
  xToHullAngle,
} from "./silhouettes.js";
export { WAVES, type Wave, type WaveEntry } from "./waves.js";
