// Generated by `bun run versus index` — do not edit.
//
// Every candidate directory under `candidates/`, in directory order. Add one by
// making the directory and running the command; a conflict here is resolved the
// same way. `test/registry.test.ts` fails when this and the tree disagree, and
// `index.ts` next door says why it is generated at all.

import type { Variant } from "../variant.js";
import { SLOW_DRAIN } from "./slow-window/drain/index.js";
import { SLOW_FOCUS } from "./slow-window/focus/index.js";
import { SLOW_FRAME } from "./slow-window/frame/index.js";
import { SLOW_GUTTER } from "./slow-window/gutter/index.js";
import { SLOW_WASH } from "./slow-window/wash/index.js";

export const VARIANTS: Variant[] = [SLOW_DRAIN, SLOW_FOCUS, SLOW_FRAME, SLOW_GUTTER, SLOW_WASH];
