// Generated by `bun run versus index` — do not edit.
//
// Every candidate directory under `candidates/`, in directory order. Add one by
// making the directory and running the command; a conflict here is resolved the
// same way. `test/registry.test.ts` fails when this and the tree disagree, and
// `index.ts` next door says why it is generated at all.

import type { Variant } from "../variant.js";
import { INSTAR_PENDULUM } from "./instar-tail/pendulum/index.js";
import { INSTAR_STATIONS } from "./instar-tail/stations/index.js";
import { LEDGER_LIT } from "./ledger-nerves/lit/index.js";
import { SCUTTLE_LOBED } from "./scuttle-seat/lobed/index.js";

export const VARIANTS: Variant[] = [
  INSTAR_PENDULUM,
  INSTAR_STATIONS,
  LEDGER_LIT,
  SCUTTLE_LOBED,
];
