import { PALETTE } from "@neon-spore/render";

/**
 * Page furniture for the break sheet.
 *
 * The same shape `tools/style-guide/src/page.ts` has and deliberately not the
 * same file: that sheet is panels of different heights down one column, this
 * one is a fixed grid of cells, and a shared helper would be two layouts
 * wearing one name. What the two share is the ground and the type, and both
 * come off `PALETTE` rather than out of either file.
 */

/** Wide enough for seven moments at a readable cell size, and no wider: the
 * owner reads this on a phone, rasterised. */
export const WIDTH = 980;
export const MONO = "Courier New, monospace";

export function esc(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

/** Two decimals, without the trailing zeroes that make a path twice as long. */
export function r(n: number): string {
  return String(Math.round(n * 100) / 100);
}

export function label(
  x: number,
  y: number,
  text: string,
  size: number,
  fill: string,
  anchor: "start" | "middle" | "end" = "start",
): string {
  return `<text x="${r(x)}" y="${r(y)}" fill="${fill}" font-family="${MONO}" font-size="${size}" text-anchor="${anchor}">${esc(text)}</text>`;
}

export function page(title: string, height: number, body: string): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${WIDTH} ${height}" width="${WIDTH}" height="${height}">
  <title>${esc(title)}</title>
  <rect width="${WIDTH}" height="${height}" fill="${PALETTE.background}"/>
  ${label(32, 40, title, 15, PALETTE.pod)}
  ${label(32, 60, "generated by `bun run breaks` from shatter.ts — every row is one tuning, every column one moment", 10, PALETTE.dim)}
${body}
</svg>
`;
}
