import { PALETTE } from "@neon-spore/render";

/**
 * Page furniture for the style-guide specimen sheet.
 *
 * It does not borrow `tools/shape-sheet/src/svg.ts` on purpose: that one is a
 * grid of equal cells, and every panel here is a different shape. What the two
 * share is the ground and the type, and those come from `PALETTE` rather than
 * from either file.
 */

export const WIDTH = 900;
export const MONO = "Courier New, monospace";

/** A run of text at a fixed size, the way every label on the sheet is drawn. */
export function label(
  x: number,
  y: number,
  text: string,
  size: number,
  fill: string,
  anchor: "start" | "middle" | "end" = "start",
): string {
  return `<text x="${r(x)}" y="${r(y)}" fill="${fill}" font-family="${MONO}" font-size="${size}" text-anchor="${anchor}">${esc(text)}</text>`;
}

/**
 * A panel: a rule, a heading, and the sentence from `docs/style-guide.md` that
 * the panel is a picture of. The sentence is the point — a specimen with no
 * claim attached is decoration, and this sheet exists to be evidence.
 */
export function panel(y: number, title: string, claim: string, body: string): string {
  return `  <g>
    <line x1="40" y1="${r(y)}" x2="${WIDTH - 40}" y2="${r(y)}" stroke="${PALETTE.grid}"/>
    ${label(40, y + 26, title, 13, PALETTE.pod)}
    ${label(40, y + 46, claim, 10, PALETTE.dim)}
${body}
  </g>`;
}

export function esc(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

/** Two decimals, without the trailing zeroes that make a path twice as long. */
export function r(n: number): string {
  return String(Math.round(n * 100) / 100);
}

export function page(title: string, height: number, body: string): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${WIDTH} ${height}" width="${WIDTH}" height="${height}">
  <title>${esc(title)}</title>
  <rect width="${WIDTH}" height="${height}" fill="${PALETTE.background}"/>
  ${label(40, 44, title, 15, PALETTE.pod)}
  ${label(40, 64, "generated by `bun run style-guide` from PALETTE, STROKE and silhouettes.ts — docs/style-guide.md", 10, PALETTE.dim)}
${body}
</svg>
`;
}
