#!/usr/bin/env bun

/**
 * `bun run raster` — regenerates every baked asset in `assets/raster/`.
 *
 * It is a build step that is deliberately *not* wired into `bun run build`.
 * The output is a look, and CLAUDE.md's *A look is offered, never replaced*
 * means a look changes when the owner decides it does, not because somebody
 * ran the build. Committing the bytes and regenerating them by hand is what
 * makes the change visible in a diff.
 *
 * Everything it writes is reproducible: same seed, same frames, same file.
 */

import { mkdir } from "node:fs/promises";
import { encodeApng } from "./src/apng.js";
import { renderBurst } from "./src/render.js";
import { BURST } from "./src/spec.js";
import { encodeAnimatedWebp } from "./src/webp.js";

const assetsDir = new URL("../../assets/raster/", import.meta.url);
const probeFile = new URL("../../packages/render/src/raster-probe.ts", import.meta.url);
const path = (name: string): string => Bun.fileURLToPath(new URL(name, assetsDir));

const base64 = (bytes: Uint8Array): string => Buffer.from(bytes).toString("base64");

const PROBE_HEADER = `// Generated by \`bun run raster\`. Do not edit by hand.
/**
 * Two tiny images whose only job is to be decoded.
 *
 * The APNG is 1x2. Its still image is opaque in both pixels and its single
 * animation frame is transparent in the lower one, so a decoder that animates
 * and a decoder that does not disagree about one alpha value — which is a
 * feature test rather than a user-agent string, and stays true when the next
 * browser changes its mind.
 *
 * The WebP is two 8x8 frames. WebP has no still fallback inside the file, so
 * a decoder that cannot animate cannot decode it at all: loading is the test.
 */
`;

async function main(): Promise<void> {
  await mkdir(assetsDir, { recursive: true });
  const rendered = await renderBurst(BURST);

  const apng = encodeApng(
    rendered.png.map((png) => ({ png, delayMs: BURST.frameMs })),
    { plays: 0 },
  );
  const webp = encodeAnimatedWebp(
    rendered.webp.map((frame) => ({ webp: frame, durationMs: BURST.frameMs })),
  );
  const probeApng = encodeApng(
    [
      { png: rendered.probePng.still, delayMs: 1000 },
      { png: rendered.probePng.animated, delayMs: 1000 },
    ],
    { plays: 0, stillIsFallback: true },
  );
  const probeWebp = encodeAnimatedWebp(
    rendered.probeWebp.map((frame) => ({ webp: frame, durationMs: 100 })),
  );

  await Promise.all([
    Bun.write(path("burst-strip.webp"), rendered.strip),
    Bun.write(path("burst.apng"), apng),
    Bun.write(path("burst.webp"), webp),
    Bun.write(
      path("burst.json"),
      `${JSON.stringify(
        {
          frames: BURST.frames,
          frameSize: BURST.size,
          frameMs: BURST.frameMs,
          spikes: BURST.spikes,
          seed: BURST.seed,
          bytes: {
            strip: rendered.strip.length,
            apng: apng.length,
            webp: webp.length,
          },
        },
        null,
        2,
      )}\n`,
    ),
    Bun.write(
      Bun.fileURLToPath(probeFile),
      `${PROBE_HEADER}
export const APNG_PROBE = "data:image/png;base64,${base64(probeApng)}";

export const ANIMATED_WEBP_PROBE = "data:image/webp;base64,${base64(probeWebp)}";
`,
    ),
  ]);

  const kb = (n: number): string => `${(n / 1024).toFixed(1)} kB`;
  console.log(
    `burst-strip.webp ${kb(rendered.strip.length)}  (${BURST.frames} frames of ${BURST.size}px)`,
  );
  console.log(`burst.apng       ${kb(apng.length)}`);
  console.log(`burst.webp       ${kb(webp.length)}`);
  console.log(`probes           apng ${probeApng.length} B, webp ${probeWebp.length} B`);
}

await main();
