/**
 * **The clock bosses' half of the surface**, written out the same way.
 *
 * Split out of `boss-surface.ts` when THE THROAT's eight names took that file
 * two lines over its 250-line limit, along the seam `bosses-clocks.ts` cuts
 * one file down: every name here belongs to a boss whose whole difficulty is a
 * beat count the pair has to say out loud, which is also why every one of them
 * is imported by a *screen* — a number nobody can hear has to be drawn.
 *
 * Next door's rule holds word for word: a name here is one something outside
 * `packages/sim` imports, and `bun run typecheck` says so either way.
 */

export {
  BATON_SOCKET_DARK,
  BATON_SOCKET_LIT,
  BATON_SOCKET_SHED,
  BATON_STAGES,
  type BatonEntry,
  type BatonStage,
  type BatonState,
  batonBaseCol,
  batonBeadCol,
  batonBeadRowMilli,
  batonBoss,
  batonDark,
  batonLandTick,
  batonLocked,
  batonSocketRow,
  CANDLE_PHASES,
  type CandleEntry,
  type CandlePhase,
  type CandleState,
  candleBoss,
  candleEating,
  candleMoving,
  DIASTOLE_PHASES,
  DIASTOLE_SIDES,
  type DiastoleEntry,
  type DiastolePhase,
  type DiastoleSide,
  type DiastoleState,
  diastoleBeating,
  diastoleBoss,
  diastoleBridgeCol,
  diastoleChamberCol,
  diastoleCoincides,
  diastoleColor,
  diastoleContracts,
  diastoleEvery,
  diastoleHits,
  diastoleSeat,
  diastoleSince,
  diastoleStanding,
  GORGE_PHASES,
  type GorgeEntry,
  type GorgeIntake,
  type GorgePhase,
  type GorgeState,
  gorgeBeads,
  gorgeBoss,
  gorgeFull,
  gorgeIntakeAt,
  gorgeNearestFull,
  gorgePhase,
  gorgeSink,
  ORRERY_PHASES,
  ORRERY_RINGS,
  // The entry alone, for now: THE ORRERY's rings are read by nothing outside
  // this package until its picture is drawn, and this file's rule is that a
  // name here is one something outside `packages/sim` imports.
  type OrreryEntry,
  type OrreryPhase,
  type OrreryState,
  orreryCoreCol,
  orreryDir,
  orreryGapSlot,
  orreryNextOpen,
  orreryOrbit,
  orreryReach,
  orreryRingBroken,
  orreryRingOpen,
  orreryShaftOpen,
  STARE_PHASES,
  type StareEntry,
  type StarePhase,
  type StareState,
  stareBoss,
  stareLooking,
  stareTellLeft,
  stareTurning,
  stareWatches,
  THROAT_PHASES,
  type ThroatEntry,
  type ThroatPhase,
  type ThroatState,
  throatBoss,
  throatEvertBeatsLeft,
  throatEvery,
  throatInhales,
  throatMouthCol,
  throatMouthRow,
  throatStride,
  throatToInhale,
} from "./bosses.js";
