/**
 * Every name the boss code puts on `@neon-spore/sim`'s surface, written out.
 *
 * `index.ts` used to say `export * from "./bosses.js"`, and `bosses.ts` is a
 * barrel of twenty more — so the package's surface was defined transitively
 * and could not be read anywhere. This file is the list, and it is the whole
 * of the file: `index.ts` re-exports it wholesale, which is safe precisely
 * because there is nothing here but names.
 *
 * A name here is one something outside `packages/sim` imports. Adding one is
 * how a boss rule leaves the package; if nothing imports it, it does not
 * belong here, and `bun run typecheck` will say so either way.
 */

// And the clock bosses' names, whole — a list of the same kind, cut for the
// same reason `bosses.ts` was (`boss-surface-clocks.ts`).
export * from "./boss-surface-clocks.js";
export {
  BOSS_KINDS,
  bossFillsWave,
  type CairnState,
  cairnState,
  cairnWaited,
  enterScoutPhase,
  FLEET_LEN_MAX,
  FLEET_LEN_MIN,
  FLEET_SHIPS_MAX,
  type FleetEntry,
  type FleetShip,
  type FleetState,
  fleetAfloat,
  fleetBeatsLeft,
  fleetCols,
  fleetFault,
  fleetIndex,
  fleetOnBoard,
  fleetRows,
  fleetShipAt,
  // A square already fired at: the director's hand on the sights reads it
  // to walk past the splashes, the way the pair reads the chart's marks.
  fleetStruck,
  GAUGE_FULL,
  GAUGE_LEAD_BEATS,
  type GaugeEntry,
  type GaugeState,
  gaugeBeatsLeft,
  gaugeHolds,
  gaugeRound,
  gaugeSeated,
  installMaze,
  MAZE_APPROACH_BEATS,
  MAZE_REASONS,
  MAZE_TURN,
  MAZE_VERDICT_BEATS,
  type MazeEntrance,
  type MazeGeometry,
  type MazeState,
  type MazeStep,
  type MazeWheel,
  MIRROR_GESTURES,
  MIRROR_LEAD_BEATS,
  MIRROR_STEPS,
  type MirrorGesture,
  type MirrorPhase,
  type MirrorState,
  type MirrorStep,
  type MirrorVerdictReason,
  mazeArc,
  mazeBottomCol,
  mazeCenterMilli,
  mazeCircleMilli,
  mazeCopyWheel,
  mazeCoreEntrance,
  mazeCosMilli,
  mazeCurrent,
  mazeEntranceAngle,
  mazeEntranceCol,
  mazeEntrances,
  mazeFault,
  mazeHeartColor,
  mazeHeartShot,
  mazeRadiusMilli,
  mazeReachesCore,
  mazeReadBeats,
  mazeRingMilli,
  mazeRound,
  mazeSinMilli,
  mazeSolveRoute,
  mazeSweep,
  mazeWheel,
  mirrorGesture,
  mirrorHoldsControls,
  mirrorListenBeats,
  NO_TETHER,
  PIN_THIN_MILLI,
  PINBALL_MORPH_BEATS,
  type PinBall,
  type PinballEntry,
  type PinballRound,
  type PinballState,
  type PinPhysics,
  type PinPiece,
  PULSE_COUNT_BEATS,
  PULSE_JUDGES,
  PULSE_LANES,
  PULSE_PHASES,
  PULSE_VERDICT_BEATS,
  type PulseEntry,
  type PulseJudge,
  type PulseLane,
  type PulseNote,
  type PulsePhase,
  type PulseStage,
  type PulseState,
  pinballFault,
  pinballHolds,
  pinballRound,
  pinCannonMilli,
  pinHeightMilli,
  pinLaneFloorMilli,
  pinLaunchVelocity,
  pinPhysics,
  pinRestingBall,
  pinTargetsLeft,
  pulseCalls,
  pulseCurrent,
  pulseEndTick,
  pulseFault,
  pulseHolds,
  pulseLaneIndex,
  pulseNoteAt,
  pulseNoteTick,
  pulseRound,
  pulseVeiled,
  QUEEN_FLANK_TILES,
  type QueenGesture,
  type QueenState,
  queenGesture,
  queenMarkCol,
  queenTorchCol,
  type RepriseEntry,
  type RepriseState,
  ROCK_CYCLE,
  repriseEchoing,
  repriseHeld,
  repriseLeft,
  type ScoutArena,
  type ScoutEntry,
  type ScoutHazard,
  type ScoutMote,
  type ScoutPhase,
  type ScoutPoint,
  type ScoutState,
  SNAKE_MORPH_BEATS,
  type SnakeEntry,
  type SnakeRound,
  type SnakeState,
  type SnakeTile,
  SPLICE_FIRST_STRAWS,
  SPLICE_SETTLE_BEATS,
  type SpliceEntry,
  type SpliceRound,
  type SpliceState,
  scoutCleared,
  scoutCurrent,
  scoutHolds,
  scoutHome,
  scoutLeft,
  scoutMawOpen,
  scoutNose,
  scoutOpenRound,
  scoutRound,
  shipCol,
  shipCovers,
  shipRow,
  snakeCrashed,
  snakeHolds,
  snakeResting,
  snakeRound,
  spliceCurrent,
  spliceEntranceRow,
  spliceNumberAt,
  spliceRound,
  spliceSpreadCol,
  spliceStraws,
  spliceWanted,
  stepBall,
  UNDERTOW_BREACH_STAGES,
  UNDERTOW_PHASES,
  type UndertowBreach,
  type UndertowBreachStage,
  type UndertowEntry,
  type UndertowPhase,
  type UndertowState,
  undertowBoss,
  undertowBowBeats,
  undertowBreachAt,
  undertowLastCol,
  undertowLobeAt,
  undertowPlateBeside,
  undertowUnseated,
  VANE_CYCLE,
  VANE_CYCLE_BEATS,
  VANE_PHASES,
  type VaneState,
  vaneColor,
  vaneCycle,
  vaneCycleBeat,
  vaneFold,
  vaneOpen,
  vaneOpening,
  vanePhase,
  vanePivotCol,
  vaneReach,
  vaneReachMilli,
  vaneStageStart,
  vaneTipCol,
  vaneWeakCol,
  WARDEN_PHASES,
  type WardenState,
  type WellEntry,
  wardenColor,
  wardenCycle,
  wardenEyeOpen,
  wardenHandleMilli,
  // The phase its plates put it in, for the STATES sheet's pose of each
  // (`tools/director/src/poses-bosses-clocks.ts`) — read, never re-derived.
  wardenPhase,
  wardenPullMilli,
  wardenTether,
} from "./bosses.js";
