/**
 * **The clock bosses' half of the surface**, written out the same way.
 *
 * Split out of `boss-surface.ts` when THE THROAT's eight names took that file
 * two lines over its 250-line limit, along the seam `bosses-clocks.ts` cuts
 * one file down: every name here belongs to a boss whose whole difficulty is a
 * beat count the pair has to say out loud, which is also why every one of them
 * is imported by a *screen* — a number nobody can hear has to be drawn.
 *
 * Next door's rule holds word for word: a name here is one something outside
 * `packages/sim` imports, and `bun run typecheck` says so either way.
 */

export {
  BATON_SOCKET_DARK,
  BATON_SOCKET_LIT,
  BATON_SOCKET_SHED,
  BATON_STAGES,
  type BatonEntry,
  type BatonStage,
  type BatonState,
  batonBaseCol,
  batonBeadCol,
  batonBeadRowMilli,
  batonBoss,
  batonDark,
  batonLandTick,
  batonLocked,
  batonSocketRow,
  CANDLE_PHASES,
  type CandleEntry,
  type CandlePhase,
  type CandleState,
  type CurtainEntry,
  type CurtainState,
  candleBoss,
  candleEating,
  candleMoving,
  curtainBody,
  curtainBoss,
  curtainCoreBare,
  curtainCovers,
  curtainLobesLeft,
  curtainReach,
  curtainSoftAt,
  curtainStride,
  DIASTOLE_PHASES,
  DIASTOLE_SIDES,
  type DiastoleEntry,
  type DiastolePhase,
  type DiastoleSide,
  type DiastoleState,
  diastoleBeating,
  diastoleBoss,
  diastoleBridgeCol,
  diastoleChamberCol,
  diastoleCoincides,
  diastoleColor,
  diastoleContracts,
  diastoleEvery,
  diastoleHits,
  diastoleSeat,
  diastoleSince,
  diastoleStanding,
  GORGE_PHASES,
  type GorgeEntry,
  type GorgeIntake,
  type GorgePhase,
  type GorgeState,
  gorgeBeads,
  gorgeBoss,
  gorgeFull,
  gorgeIntakeAt,
  gorgeNearestFull,
  gorgePhase,
  gorgeSink,
  NO_RING,
  ORRERY_PHASES,
  ORRERY_RINGS,
  type OrreryEntry,
  type OrreryPhase,
  type OrreryState,
  orreryCoreCol,
  orreryDir,
  orreryGapSlot,
  // The hand's two questions, asked by the picture and by the hit test: which
  // ring a thumb is on, and whether one is on it (`orrery-hand.ts`).
  orreryHandHolds,
  orreryHandRing,
  orreryNextOpen,
  orreryOrbit,
  orreryReach,
  orreryRingBroken,
  orreryRingOpen,
  orreryShaftOpen,
  // And the rate the three rigs with no finger turn a ring at, asked for in
  // all three rather than chosen in any (`orrery-hand.ts`).
  orreryTurnPerTickMilli,
  type SinewEntry,
  type SinewState,
  STARE_PHASES,
  type StareEntry,
  type StarePhase,
  type StareState,
  sinewBandMilli,
  sinewBoss,
  sinewDecaying,
  sinewGone,
  sinewHeld,
  sinewInZone,
  sinewMassLeft,
  sinewMassRow,
  sinewPull,
  sinewSum,
  sinewSwinging,
  sinewWalked,
  sinewZone,
  sinewZoneWidth,
  stareBoss,
  stareLooking,
  stareTellLeft,
  stareTurning,
  stareWatches,
  // THE TASTER's entry, which authors nothing — the director's own guard
  // narrows on it (`tools/director/src/boss-nothing.ts`).
  type TasterEntry,
  THROAT_PHASES,
  type ThroatEntry,
  type ThroatPhase,
  type ThroatState,
  throatBoss,
  throatEvertBeatsLeft,
  throatEvery,
  throatInhales,
  throatMouthCol,
  throatMouthRow,
  throatStride,
  throatToInhale,
} from "./bosses.js";
