/**
 * Every name the boss code puts on `@neon-spore/sim`'s surface, written out.
 *
 * `index.ts` used to say `export * from "./bosses.js"`, and `bosses.ts` is a
 * barrel of twenty more — so the package's surface was defined transitively
 * and could not be read anywhere. This file is the list, and it is the whole
 * of the file: `index.ts` re-exports it wholesale, which is safe precisely
 * because there is nothing here but names.
 *
 * A name here is one something outside `packages/sim` imports. Adding one is
 * how a boss rule leaves the package; if nothing imports it, it does not
 * belong here, and `bun run typecheck` will say so either way.
 */

export {
  BOSS_KINDS,
  bossFillsWave,
  FLEET_LEN_MAX,
  FLEET_LEN_MIN,
  FLEET_SHIPS_MAX,
  type FleetEntry,
  type FleetShip,
  type FleetState,
  fleetBeatsLeft,
  fleetCols,
  fleetFault,
  fleetOnBoard,
  fleetRows,
  fleetShipAt,
  GAUGE_FULL,
  GAUGE_LEAD_BEATS,
  type GaugeState,
  gaugeHolds,
  gaugeRound,
  gaugeSeated,
  installMaze,
  MAZE_APPROACH_BEATS,
  MAZE_TURN,
  type MazeEntrance,
  type MazeGeometry,
  type MazeState,
  type MazeStep,
  type MazeWheel,
  MIRROR_LEAD_BEATS,
  MIRROR_STEPS,
  type MirrorPhase,
  type MirrorState,
  type MirrorStep,
  type MirrorVerdictReason,
  mazeArc,
  mazeBottomCol,
  mazeCenterMilli,
  mazeCircleMilli,
  mazeCopyWheel,
  mazeCoreEntrance,
  mazeCurrent,
  mazeEntranceAngle,
  mazeEntranceCol,
  mazeEntrances,
  mazeFault,
  mazeHeartColor,
  mazeHeartShot,
  mazeRadiusMilli,
  mazeRingMilli,
  mazeRound,
  mazeSolveRoute,
  mazeSweep,
  mazeWheel,
  mirrorHoldsControls,
  mirrorListenBeats,
  NO_TETHER,
  PIN_THIN_MILLI,
  PINBALL_MORPH_BEATS,
  type PinBall,
  type PinballEntry,
  type PinballRound,
  type PinballState,
  type PinPhysics,
  type PinPiece,
  pinballFault,
  pinballHolds,
  pinHeightMilli,
  pinLaunchVelocity,
  pinPhysics,
  pinRestingBall,
  pinTargetsLeft,
  QUEEN_FLANK_TILES,
  type QueenState,
  queenMarkCol,
  queenTorchCol,
  ROCK_CYCLE,
  SNAKE_MORPH_BEATS,
  type SnakeEntry,
  type SnakeRound,
  type SnakeState,
  type SnakeTile,
  shipCol,
  shipCovers,
  shipRow,
  snakeHolds,
  snakeRound,
  stepBall,
  VANE_CYCLE,
  VANE_CYCLE_BEATS,
  VANE_PHASES,
  type VaneState,
  vaneColor,
  vaneCycle,
  vaneCycleBeat,
  vaneFold,
  vaneOpen,
  vaneOpening,
  vanePhase,
  vanePivotCol,
  vaneReach,
  vaneReachMilli,
  vaneStageStart,
  vaneTipCol,
  vaneWeakCol,
  WARDEN_PHASES,
  type WardenState,
  wardenColor,
  wardenCycle,
  wardenEyeOpen,
  wardenHandleMilli,
  wardenPullMilli,
  wardenTether,
} from "./bosses.js";
