/**
 * Every name the boss code puts on `@neon-spore/sim`'s surface, written out.
 *
 * `index.ts` used to say `export * from "./bosses.js"`, and `bosses.ts` is a
 * barrel of twenty more — so the package's surface was defined transitively
 * and could not be read anywhere. This file is the list, and it is the whole
 * of the file: `index.ts` re-exports it wholesale, which is safe precisely
 * because there is nothing here but names.
 *
 * A name here is one something outside `packages/sim` imports. Adding one is
 * how a boss rule leaves the package; if nothing imports it, it does not
 * belong here, and `bun run typecheck` will say so either way.
 */

export {
  BATON_SOCKET_DARK,
  BATON_SOCKET_LIT,
  BATON_SOCKET_SHED,
  BATON_STAGES,
  type BatonEntry,
  type BatonStage,
  type BatonState,
  BOSS_KINDS,
  batonBaseCol,
  batonBeadCol,
  batonBeadRowMilli,
  batonBoss,
  batonDark,
  batonLandTick,
  batonLocked,
  batonSocketRow,
  bossFillsWave,
  type CairnState,
  cairnState,
  cairnWaited,
  DIASTOLE_PHASES,
  DIASTOLE_SIDES,
  type DiastoleEntry,
  type DiastolePhase,
  type DiastoleSide,
  type DiastoleState,
  diastoleBeating,
  diastoleBoss,
  diastoleBridgeCol,
  diastoleChamberCol,
  diastoleCoincides,
  diastoleColor,
  diastoleContracts,
  diastoleEvery,
  diastoleHits,
  diastoleSeat,
  diastoleSince,
  diastoleStanding,
  FLEET_LEN_MAX,
  FLEET_LEN_MIN,
  FLEET_SHIPS_MAX,
  type FleetEntry,
  type FleetShip,
  type FleetState,
  fleetBeatsLeft,
  fleetCols,
  fleetFault,
  fleetIndex,
  fleetOnBoard,
  fleetRows,
  fleetShipAt,
  GAUGE_FULL,
  GAUGE_LEAD_BEATS,
  type GaugeEntry,
  type GaugeState,
  gaugeBeatsLeft,
  gaugeHolds,
  gaugeRound,
  gaugeSeated,
  installMaze,
  MAZE_APPROACH_BEATS,
  MAZE_REASONS,
  MAZE_TURN,
  MAZE_VERDICT_BEATS,
  type MazeEntrance,
  type MazeGeometry,
  type MazeState,
  type MazeStep,
  type MazeWheel,
  MIRROR_LEAD_BEATS,
  MIRROR_STEPS,
  type MirrorPhase,
  type MirrorState,
  type MirrorStep,
  type MirrorVerdictReason,
  mazeArc,
  mazeBottomCol,
  mazeCenterMilli,
  mazeCircleMilli,
  mazeCopyWheel,
  mazeCoreEntrance,
  mazeCosMilli,
  mazeCurrent,
  mazeEntranceAngle,
  mazeEntranceCol,
  mazeEntrances,
  mazeFault,
  mazeHeartColor,
  mazeHeartShot,
  mazeRadiusMilli,
  mazeReachesCore,
  mazeReadBeats,
  mazeRingMilli,
  mazeRound,
  mazeSinMilli,
  mazeSolveRoute,
  mazeSweep,
  mazeWheel,
  mirrorHoldsControls,
  mirrorListenBeats,
  NO_TETHER,
  PIN_THIN_MILLI,
  PINBALL_MORPH_BEATS,
  type PinBall,
  type PinballEntry,
  type PinballRound,
  type PinballState,
  type PinPhysics,
  type PinPiece,
  PULSE_COUNT_BEATS,
  PULSE_JUDGES,
  PULSE_LANES,
  PULSE_PHASES,
  PULSE_VERDICT_BEATS,
  type PulseEntry,
  type PulseJudge,
  type PulseLane,
  type PulseNote,
  type PulsePhase,
  type PulseStage,
  type PulseState,
  pinballFault,
  pinballHolds,
  pinballRound,
  pinCannonMilli,
  pinHeightMilli,
  pinLaneFloorMilli,
  pinLaunchVelocity,
  pinPhysics,
  pinRestingBall,
  pinTargetsLeft,
  pulseCalls,
  pulseCurrent,
  pulseEndTick,
  pulseFault,
  pulseHolds,
  pulseLaneIndex,
  pulseNoteAt,
  pulseNoteTick,
  pulseRound,
  pulseVeiled,
  QUEEN_FLANK_TILES,
  type QueenState,
  queenMarkCol,
  queenTorchCol,
  type RepriseEntry,
  type RepriseState,
  ROCK_CYCLE,
  repriseEchoing,
  repriseHeld,
  repriseLeft,
  type ScoutArena,
  type ScoutEntry,
  type ScoutHazard,
  type ScoutMote,
  type ScoutState,
  SNAKE_MORPH_BEATS,
  type SnakeEntry,
  type SnakeRound,
  type SnakeState,
  type SnakeTile,
  SPLICE_FIRST_STRAWS,
  SPLICE_SETTLE_BEATS,
  type SpliceEntry,
  type SpliceRound,
  type SpliceState,
  STARE_PHASES,
  type StareEntry,
  type StarePhase,
  type StareState,
  scoutCleared,
  scoutCurrent,
  scoutHolds,
  scoutLeft,
  scoutRound,
  shipCol,
  shipCovers,
  shipRow,
  snakeCrashed,
  snakeHolds,
  snakeResting,
  snakeRound,
  spliceCurrent,
  spliceEntranceRow,
  spliceNumberAt,
  spliceRound,
  spliceSpreadCol,
  spliceStraws,
  spliceWanted,
  stareBoss,
  stareLooking,
  stareTellLeft,
  stareTurning,
  stareWatches,
  stepBall,
  VANE_CYCLE,
  VANE_CYCLE_BEATS,
  VANE_PHASES,
  type VaneState,
  vaneColor,
  vaneCycle,
  vaneCycleBeat,
  vaneFold,
  vaneOpen,
  vaneOpening,
  vanePhase,
  vanePivotCol,
  vaneReach,
  vaneReachMilli,
  vaneStageStart,
  vaneTipCol,
  vaneWeakCol,
  WARDEN_PHASES,
  type WardenState,
  type WellEntry,
  wardenColor,
  wardenCycle,
  wardenEyeOpen,
  wardenHandleMilli,
  wardenPullMilli,
  wardenTether,
} from "./bosses.js";
