// Generated by `bun run raster`. Do not edit by hand.
/**
 * Two tiny images whose only job is to be decoded.
 *
 * The APNG is 1x2. Its still image is opaque in both pixels and its single
 * animation frame is transparent in the lower one, so a decoder that animates
 * and a decoder that does not disagree about one alpha value — which is a
 * feature test rather than a user-agent string, and stays true when the next
 * browser changes its mind.
 *
 * The WebP is two 8x8 frames. WebP has no still fallback inside the file, so
 * a decoder that cannot animate cannot decode it at all: loading is the test.
 */

export const APNG_PROBE =
  "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAACCAYAAACZgbYnAAAACGFjVEwAAAABAAAAALQt6aAAAAAYSURBVHgBYvrP8P8/EwMDAwMAAAD//wMAFhIDAhuZRxEAAAAaZmNUTAAAAAAAAAABAAAAAgAAAAAAAAAAA+gD6AEASZoXyAAAABxmZEFUAAAAAXgBYvrP8P8/EyMDIyMAAAD//wMAFhkDBbkxtlsAAAAASUVORK5CYII=";

export const ANIMATED_WEBP_PROBE =
  "data:image/webp;base64,UklGRswAAABXRUJQVlA4WAoAAAASAAAABwAABwAAQU5JTQYAAAAAAAAAAABBTk1GTAAAAAAAAAAAAAcAAAcAAGQAAANWUDggNAAAAPABAJ0BKggACAAAwBIloAJ0ugH4AATIAAD+Ex/79pe9APegH+rn/73T/e6f73T/97JAAABBTk1GTAAAAAAAAAAAAAcAAAcAAGQAAANWUDggNAAAANABAJ0BKggACAAAwBIloAJ0ugH4AAOwAP73tB//aWfrQ/qWf48v/3rK+9ZX3rK/73/AAAA=";
